name = "hello-gfalcon"
license = "MIT"
licenselink = "https://github.com/oleksii-khalikov/hugo-theme-hello-gfalcon/blob/master/LICENSE.md"
homepage = "https://github.com/oleksii-khalikov/hugo-theme-hello-gfalcon"
description = "A simple theme for Hugo. That's it."
tags = ["blog", "clean", "customizable", "dark", "highlighting", "light", "minimal", "monochromatic", "multilingual", "personal", "responsive", "simple", "technical"]
features = ["blog", "shortcode", "syntax highlighting"]
min_version = 0.30

[author]
  name = "gfalcon"
  homepage = "https://gfalcon.com.ua"
  x = "https://x.com/GFalconUA"

[original]
  name = "hello-coolapso"
  homepage = "https://github.com/coolapso/hugo-theme-hello-4s3ti"
  repo = "https://github.com/coolapso/hugo-theme-hello-4s3ti"
